name: vaultmind
description: VaultMind - A privacy-focused AI assistant that connects to laptop-hosted Ollama LLM via Tailscale

# Prevent accidental publishing to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  cupertino_icons: ^1.0.6

  # State management
  provider: ^6.1.1
  get_it: ^7.6.4

  # Navigation
  go_router: ^12.1.3

  # Network & HTTP
  http: ^1.1.2
  dio: ^5.4.0
  connectivity_plus: ^5.0.2

  # Voice to text
  speech_to_text: ^6.6.0
  permission_handler: ^11.1.0

  # UI & Design
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0

  # Local storage & offline support
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

  # Utils & helpers
  uuid: ^4.2.1
  intl: ^0.19.0
  logger: ^2.0.2+1

  # Development
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/

  # Fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic